"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),path=require("path");
const root=path.resolve(__dirname,"..");
const sb={globalThis:null,Date,Math,Float32Array}; sb.globalThis=sb;
vm.runInContext(fs.readFileSync(path.join(root,"scene-engine.js"),"utf8"),vm.createContext(sb));
const e=sb.YurikaSceneEngine; assert(e);
const freq=new Float32Array(1024); freq.fill(-48); for(let i=260;i<700;i++)freq[i]=-30;
const time=new Float32Array(2048); for(let i=0;i<time.length;i++)time[i]=Math.sin(i*0.12)*0.12;
const settings={sceneEnabled:true,sceneStrength:70,sceneExponent:1.15,sceneInertia:60,sparkEnabled:true,sparkAmount:70,impactEnabled:true,impactAmount:65,deviceProfile:"stereo",multiSpeakerEnabled:true,multiSpeakerAmount:55,width:20,perspectiveEnabled:false,perspectiveDepth:0,detail:25,reality:15,lowCutHz:35,bassDb:1.5,warmthDb:0,airDb:1};
let r=e.updateRuntime(null,freq,time,48000,settings,0.05);
assert(r.patternId>=0&&r.patternId<78125); assert(r.accent>=0&&r.accent<=99); assert(r.controls.width>=0&&r.controls.width<=68); assert(r.controls.virtualMulti.rear>=0);
const phone=e.deriveControls({...settings,deviceProfile:"smartphone",bassDb:5,lowCutHz:25},r.dna,r.features);
assert(phone.lowCutHz>=72); assert(phone.bassDb<=0.25); assert(phone.width<=24); assert(phone.perspectiveDepth<=18);
const off=e.deriveControls({...settings,sceneEnabled:false,sparkEnabled:false,multiSpeakerEnabled:false,deviceProfile:"stereo"},r.dna,r.features);
assert(Math.abs(off.width-settings.width)<1e-9);
const quiet=e.deriveFastSparkDelta({...settings,sparkAmount:45,deviceProfile:"stereo"},0.05);
assert.equal(quiet.sparkMakeupDb,0); assert.equal(quiet.widthDelta,0);
const strong=e.deriveFastSparkDelta({...settings,sparkAmount:45,deviceProfile:"stereo"},0.75);
assert(strong.sparkWeight>0); assert(strong.sparkMakeupDb>=0.30&&strong.sparkMakeupDb<=0.60); assert(strong.impactGain>0);
const strongCompressed=e.deriveFastSparkDelta({...settings,sparkAmount:45,deviceProfile:"stereo",compressor:true},0.75); assert(strongCompressed.compressorEscape>0);
const full=e.deriveFastSparkDelta({...settings,sparkAmount:100,deviceProfile:"stereo"},1);
assert(full.sparkMakeupDb>0.79&&full.sparkMakeupDb<=0.80+1e-9);
const phonePulse=e.deriveFastSparkDelta({...settings,sparkAmount:100,deviceProfile:"smartphone"},1);
assert(phonePulse.sparkMakeupDb<=0.20+1e-9); assert(phonePulse.impactGain<=0.075+1e-9);
const base={width:31,detail:42,reality:27};
const added=e.composeFastSparkTargets(base,strongCompressed,"stereo",0);
assert(added.width>=base.width&&added.detail>=base.detail&&added.reality>=base.reality&&added.sparkMakeupDb>=0&&added.impactGain>0&&added.compressorEscape>0);
const pressured=e.composeFastSparkTargets(base,strongCompressed,"stereo",1);
assert.equal(pressured.width,base.width); assert.equal(pressured.detail,base.detail); assert.equal(pressured.reality,base.reality); assert.equal(pressured.sparkMakeupDb,0); assert.equal(pressured.impactGain,0); assert.equal(pressured.compressorEscape,0);
console.log("PASS scene_engine_test 78,125 cells + additive Fast Spark + Impact Liberation + pressure kill + device caps + Multi controls");
