"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),path=require("path");
const root=path.resolve(__dirname,"..");
class P{constructor(v=0){this.value=v;}cancelScheduledValues(){}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}}
class N{constructor(){this.frequency=new P();this.gain=new P(1);this.Q=new P();this.delayTime=new P();this.curve=null;this.oversample='none';}connect(n){return n;}disconnect(){}}
class B{constructor(c,l){this.d=Array.from({length:c},()=>new Float32Array(l));}getChannelData(i){return this.d[i];}}
class Ctx{constructor(sr=48000){this.sampleRate=sr;this.currentTime=1;}createBiquadFilter(){return new N();}createGain(){return new N();}createWaveShaper(){return new N();}createConvolver(){return new N();}createDelay(){return new N();}createBuffer(c,l){return new B(c,l);}createChannelSplitter(){return new N();}createChannelMerger(){return new N();}}
const sb={console,Float32Array,globalThis:null};sb.globalThis=sb;const cx=vm.createContext(sb);for(const f of ['modular-core.js','dsp-core.js','audio-modules.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),cx);
const A=sb.YurikaAudioModules,C=sb.YurikaAudioCore,ctx=new Ctx(),input=new N();
const stages={dac:A.createDacMatrixStage(ctx,input),room:A.createRoomStage(ctx,input),integrity:A.createIntegrityStage(ctx,input),cart:A.createCartridgeStage(ctx,input)};
let settings=C.sanitizeSettings({...C.DEFAULTS,dacMatrixMode:'fusion',dacMatrixStrength:77.7,dacAkmWeight:40,dacEssWeight:30,dacTiWeight:30,roomEnabled:true,roomMode:'diffusion',roomAmount:55.5,integrityEnabled:true,integrityMode:'stabilizer',integrityStrength:88.8,cartridgeEnabled:true,cartridgeMode:'mix',cartridgeMixA:40,cartridgeMixB:35,cartridgeMixC:25});
A.applyDacMatrixStage(stages.dac.stage,settings,ctx,true);A.applyRoomStage(stages.room.stage,settings,ctx);A.applyIntegrityStage(stages.integrity.stage,settings,ctx);A.applyCartridgeStage(stages.cart.stage,settings,ctx);
assert(stages.dac.stage.harm.gain.value>=0);assert.equal(stages.dac.stage.bypass.gain.value,0);assert.equal(stages.dac.stage.processed.gain.value,1);assert(stages.room.stage.wet.gain.value>0);assert.equal(stages.room.stage.bypass.gain.value,0);assert.equal(stages.room.stage.processed.gain.value,1);assert.equal(stages.integrity.stage.processed.gain.value,1);assert.equal(stages.cart.stage.direct.gain.value,0);assert(Math.abs(stages.cart.stage.ag.gain.value+stages.cart.stage.bg.gain.value+stages.cart.stage.cg.gain.value-1)<1e-9);
settings=C.sanitizeSettings({...settings,roomEnabled:false,integrityEnabled:false,cartridgeEnabled:false,dacMatrixMode:'off'});A.applyDacMatrixStage(stages.dac.stage,settings,ctx);A.applyRoomStage(stages.room.stage,settings,ctx);A.applyIntegrityStage(stages.integrity.stage,settings,ctx);A.applyCartridgeStage(stages.cart.stage,settings,ctx);assert.equal(stages.dac.stage.bypass.gain.value,1);assert.equal(stages.dac.stage.processed.gain.value,0);assert.equal(stages.room.stage.wet.gain.value,0);assert.equal(stages.room.stage.bypass.gain.value,1);assert.equal(stages.room.stage.processed.gain.value,0);assert.equal(stages.integrity.stage.bypass.gain.value,1);assert.equal(stages.cart.stage.direct.gain.value,1);
const deckNodes={A:A.createDeckBranch(ctx,new N(),new N()),B:A.createDeckBranch(ctx,new N(),new N())};settings=C.sanitizeSettings({...settings,djEnabled:true,djCrossfader:0,deckAGainDb:0,deckBGainDb:0});A.applyDecks(deckNodes,settings,ctx);assert(Math.abs(deckNodes.A.xfade.gain.value**2+deckNodes.B.xfade.gain.value**2-1)<1e-9);
console.log('PASS audio_modules_test graph builders + true DAC/room/integrity/cartridge bypass + correlated cartridge unity + equal-power deck mix');
