"use strict";
const fs=require('fs'), vm=require('vm'), assert=require('assert');
const root=require('path').resolve(__dirname,'..');
const ctx={globalThis:{}}; ctx.globalThis=ctx; vm.createContext(ctx);
vm.runInContext(fs.readFileSync(require('path').join(root,'dsp-core.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(require('path').join(root,'concert-hall.js'),'utf8').replace(/async function createStage[\s\S]*?function smooth\(/,'async function createStage(){return null;}\n  function smooth('),ctx);
const C=ctx.YurikaAudioCore, H=ctx.YurikaConcertHall;
assert(C.DEFAULTS.concertHallEnabled===false);
assert(C.DEFAULTS.concertHallMode==='reference-shoebox');
assert(C.DEFAULTS.concertHallOccupancy===70);
assert(C.SETTINGS_KEYS.includes('concertHallOccupancy'));
assert(C.SETTINGS_KEYS.includes('concertHallEnabled'));
const hp=H.computeParameters(C.sanitizeSettings({...C.DEFAULTS,concertHallEnabled:true,concertHallAmount:55,concertHallMode:'reference-shoebox',concertHallSeat:'center',deviceProfile:'headphone'}),{profile:{deviceType:'headphone'}});
const sp=H.computeParameters(C.sanitizeSettings({...C.DEFAULTS,concertHallEnabled:true,concertHallAmount:55,concertHallMode:'reference-shoebox',concertHallSeat:'center',deviceProfile:'stereo'}),{profile:{deviceType:'speaker'}});
assert(hp.enabled && sp.enabled);
assert(hp.rt60>=1.8 && hp.rt60<=2.2);
assert(hp.serialAddedLatencyMs===0);
assert(hp.wet<sp.wet,'headphone adaptation should reduce wet field');
const rear=H.computeParameters({...C.DEFAULTS,concertHallEnabled:true,concertHallAmount:55,concertHallSeat:'rear'},null);
const front=H.computeParameters({...C.DEFAULTS,concertHallEnabled:true,concertHallAmount:55,concertHallSeat:'front'},null);
assert(rear.predelayMs>front.predelayMs && rear.wet>front.wet);
const offscreen=fs.readFileSync(require('path').join(root,'offscreen.js'),'utf8');
assert(offscreen.includes('concertHall.output.connect(autoLevel)'));
assert(!offscreen.includes('concertHall.output.connect(transientValley)'));
const html=fs.readFileSync(require('path').join(root,'offscreen.html'),'utf8');
assert(html.includes('concert-hall.js'));
const popup=fs.readFileSync(require('path').join(root,'popup.html'),'utf8');
assert(popup.includes('id="concertHallOccupancy"'));
const empty=H.computeParameters({...C.DEFAULTS,concertHallEnabled:true,concertHallOccupancy:0},null);
const full=H.computeParameters({...C.DEFAULTS,concertHallEnabled:true,concertHallOccupancy:100},null);
assert(empty.rt60>full.rt60 && empty.dampingHz>full.dampingHz,'audience absorption should slightly shorten/darken the field');
console.log('concert hall contract: PASS',JSON.stringify({hpWet:hp.wet,spWet:sp.wet,rt60:hp.rt60,frontPredelay:front.predelayMs,rearPredelay:rear.predelayMs}));
