"use strict";
const fs=require("fs"),vm=require("vm"),path=require("path");
const root=path.resolve(__dirname,"..");
for(const f of ["dsp-core.js","spatial-device-profiles.js","spatial-engine.js"]) vm.runInThisContext(fs.readFileSync(path.join(root,f),"utf8"),{filename:f});
const C=globalThis.YurikaAudioCore,P=globalThis.YurikaSpatialDeviceProfiles,E=globalThis.YurikaSpatialEngine;
const a=(x,m)=>{if(!x)throw new Error(m)};
const settings=C.sanitizeSettings({...C.DEFAULTS,spatialEnabled:true,spatialMode:"natural",spatialDeviceProfile:"generic-headphone",deviceProfile:"headphone",hrtfEnabled:true,hrtfProfile:"natural",hrtfAmount:42});
const resolved=P.resolve({requestedProfile:"generic-headphone",outputTarget:"local",label:"",legacyDeviceProfile:"headphone",headphoneIntent:true});
const q=E.computeParameters(settings,{resolved,sampleRate:48000,inputChannels:2,scene:{}});
a(q.hrtfAlreadyActive===true,"HRTF active state not detected");
a(Math.abs(q.cuePreservationFactor-0.30)<1e-9,"local headphone cue preservation factor changed");
a(q.sideGain<1.07,"post-HRTF side gain still too strong");
a(q.sideDelaySeconds<0.00005,"post-HRTF side delay still too strong");
const remoteResolved=P.resolve({requestedProfile:"auto",outputTarget:"sonobus-mobile-headphones",label:"",legacyDeviceProfile:"stereo"});
const remoteSettings=C.sanitizeSettings({...C.DEFAULTS,spatialEnabled:true,spatialMode:"natural",spatialOutputTarget:"sonobus-mobile-headphones",spatialDeviceProfile:"auto",deviceProfile:"headphone",hrtfEnabled:true,hrtfProfile:"natural",hrtfAmount:30});
const rq=E.computeParameters(remoteSettings,{resolved:remoteResolved,sampleRate:48000,inputChannels:2,scene:{}});
a(Math.abs(rq.cuePreservationFactor-0.26)<1e-9,"remote binaural cue preservation factor changed");
a(rq.sideGain<1.05,"remote post-HRTF side gain too strong");
const off=fs.readFileSync(path.join(root,"offscreen.js"),"utf8");
a(/remoteBinaural && !next\.hrtfEnabled \? "natural"/.test(off),"SonoBus fallback HRTF is not natural");
a(/Math\.max\(30,Number\(next\.hrtfAmount\)\|\|0\)/.test(off),"SonoBus fallback minimum HRTF amount is not 30");
console.log(JSON.stringify({ok:true,local:{cue:q.cuePreservationFactor,sideGain:q.sideGain,sideDelayMs:q.sideDelaySeconds*1000},remote:{cue:rq.cuePreservationFactor,sideGain:rq.sideGain,sideDelayMs:rq.sideDelaySeconds*1000}}));
