"use strict";
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
const code=['modular-core.js','dsp-core.js','self-dap-core.js','audio-modules.js'].map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n')+'\n'+fs.readFileSync(path.join(root,'offscreen.js'),'utf8')+'\nglobalThis.__state=()=>state;';
function next(l,m){return new Promise((res,rej)=>{const t=setTimeout(()=>rej(new Error('timeout')),1500);l(m,{},v=>{clearTimeout(t);res(v);});});}
class P{constructor(v=0){this.value=v;}cancelScheduledValues(){}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}}
class N{constructor(){this.frequency=new P();this.gain=new P(1);this.Q=new P();this.threshold=new P();this.knee=new P();this.ratio=new P(1);this.attack=new P();this.release=new P();this.delayTime=new P();this.reduction=0;this.port={postMessage(){},onmessage:null};this.fftSize=2048;this.frequencyBinCount=1024;this.timeValue=0.1;}connect(n){return n;}disconnect(){}getFloatFrequencyData(a){a.fill(-45);}getFloatTimeDomainData(a){a.fill(this.timeValue);}}
class B{constructor(c,l){this.d=Array.from({length:c},()=>new Float32Array(l));}getChannelData(i){return this.d[i];}}
class C{constructor(o={}){this.state='running';this.currentTime=1;this.sampleRate=o.sampleRate||48000;this.destination=new N();this.audioWorklet={addModule:async()=>{}};}createMediaStreamSource(){return new N();}createBiquadFilter(){return new N();}createGain(){return new N();}createDynamicsCompressor(){return new N();}createWaveShaper(){return new N();}createConvolver(){return new N();}createChannelSplitter(){return new N();}createChannelMerger(){return new N();}createDelay(){return new N();}createAnalyser(){return new N();}createBuffer(c,l){return new B(c,l);}async resume(){}async close(){this.state='closed';}}
class W extends N{}
(async()=>{let listener;const tr={stop(){},addEventListener(){},getSettings:()=>({channelCount:2})};const stream={getTracks:()=>[tr],getAudioTracks:()=>[tr]};const sb={console,Date,Math,Float32Array,performance:{now:()=>1000},setTimeout,clearTimeout,setInterval:()=>1,clearInterval:()=>{},AudioContext:C,AudioWorkletNode:W,navigator:{mediaDevices:{getUserMedia:async()=>stream}},chrome:{runtime:{getURL:p=>p,sendMessage:async()=>({ok:true}),onMessage:{addListener:f=>listener=f}}},globalThis:null};sb.globalThis=sb;vm.runInContext(code,vm.createContext(sb));
let r=await next(listener,{target:'offscreen',type:'START',tabId:1,streamId:'s',revision:1,settings:{enabled:true,autoLevelEnabled:true,autoLevelProfile:'reference'}});assert(r.ok);let st=sb.__state();st.nodes.sharedAnalyser.timeValue=0.1;for(let i=0;i<12;i++)sb.autoLevelTick();assert(Math.abs(st.autoLevelDb)<0.3,'-20 dBFS should stay around unity');
st.nodes.sharedAnalyser.timeValue=0.01;for(let i=0;i<80;i++)sb.autoLevelTick();assert(st.autoLevelDb<=6&&st.autoLevelDb>5.5,'quiet input bounded at +6');
st.nodes.sharedAnalyser.timeValue=0.5;for(let i=0;i<140;i++)sb.autoLevelTick();assert(st.autoLevelDb>=-12&&st.autoLevelDb<-11.5,'hot input bounded at -12');
r=await next(listener,{target:'offscreen',type:'UPDATE_SETTINGS',revision:2,settings:{autoLevelEnabled:false}});sb.autoLevelTick();assert.equal(sb.__state().autoLevelDb,0);assert.equal(sb.__state().nodes.autoLevel.gain.value,1);await next(listener,{target:'offscreen',type:'STOP'});console.log('PASS auto_level_runtime_test target tracking + +6/-12 bounds + off unity');})().catch(e=>{console.error(e);process.exit(1);});
