"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),path=require("path");
const root=path.resolve(__dirname,"..");
const sb={console,globalThis:null}; sb.globalThis=sb;
vm.runInContext(fs.readFileSync(path.join(root,"dsp-core.js"),"utf8"),vm.createContext(sb));
const C=sb.YurikaAudioCore;
assert(Math.abs(C.webAudioResonanceDb(Math.SQRT1_2)+3.01029995664)<1e-9);
assert(C.webAudioResonanceDb(0.7)<-3.09 && C.webAudioResonanceDb(0.7)>-3.10);
const off=fs.readFileSync(path.join(root,"offscreen.js"),"utf8");
assert(off.includes('applyLowCutRouting(nodes, next.lowCutHz'));
assert(off.includes('noise.node.connect(lowCutBypass)'));
assert(off.includes('lowCutProcessed.connect(lowCutSum)'));
assert(!off.includes('abSum.connect(selfLimiter)'));
assert(off.includes('adaptiveTrim.connect(limiter)'));
assert(off.includes('limiter.connect(safetyMeter.node)'));
const modules=fs.readFileSync(path.join(root,"audio-modules.js"),"utf8");
assert(modules.includes('C.webAudioResonanceDb(q)'));
assert(modules.includes('stage.lowpass.Q.value=C.webAudioResonanceDb(p.q)'));
console.log('PASS final_audio_contract_test WebAudio Q semantics + neutral true bypass + redundant Self-DAP limiter removal + final safety retained');
