import json,pathlib,re,sys
root=pathlib.Path(__file__).resolve().parents[1];checks=[]
def ok(name,cond):checks.append((name,bool(cond)))
manifest=json.loads((root/'manifest.json').read_text(encoding='utf-8'))
ok('manifest_v3',manifest.get('manifest_version')==3);ok('version_3_0_0',manifest.get('version')=='3.0.0');ok('chrome_116',int(manifest.get('minimum_chrome_version','0'))>=116)
ok('permissions_v28',{'storage','activeTab','tabCapture','offscreen','tabs'}.issubset(set(manifest.get('permissions',[]))));ok('youtube_host_permissions',any('youtube.com' in x for x in manifest.get('host_permissions',[])));ok('service_worker',manifest.get('background',{}).get('service_worker')=='service-worker.js')
for name in ['modular-core.js','dsp-core.js','audio-modules.js','self-dap-core.js','scene-engine.js','adaptive-v26.js','adaptive-v27.js','adaptive-v28.js','adaptive-v29.js','headphone-profiles.js','service-worker.js','offscreen.js','popup.js','noise-worklet.js','safety-meter-worklet.js','spark-monitor-worklet.js','spatial-metrics-worklet.js','youtube-av-sync.js']:
    text=(root/name).read_text(encoding='utf-8');ok(f'no_eval_{name}',not re.search(r'\beval\s*\(|\bnew\s+Function\b',text));ok(f'no_network_{name}',not re.search(r'\bfetch\s*\(|XMLHttpRequest|WebSocket',text))
sw=(root/'service-worker.js').read_text(encoding='utf-8');off=(root/'offscreen.js').read_text(encoding='utf-8');core=(root/'dsp-core.js').read_text(encoding='utf-8');html=(root/'popup.html').read_text(encoding='utf-8')
ok('offscreen_path_declared','const OFFSCREEN_PATH = "offscreen.html"' in sw);ok('workers_reason','"WORKERS"' in sw);ok('youtube_gate','isYoutubeUrl' in core and 'youtube.com' in core and 'isYoutubeUrl' in sw)
ok('audio_only_capture','video: false' in off);ok('audio_worklet','audioWorklet.addModule' in off and 'yurika-noise-suppressor' in off);ok('noise_worklet_file',(root/'noise-worklet.js').exists());ok('safety_worklet_file',(root/'safety-meter-worklet.js').exists());ok('spark_worklet_file',(root/'spark-monitor-worklet.js').exists())
ok('detail_shaper','createWaveShaper' in off and 'detailShaper' in off);ok('oversampling','"4x"' in off and '"2x"' in off);ok('width_matrix','createChannelSplitter' in off and 'createChannelMerger' in off)
ok('reality_convolver','createConvolver' in off and 'createEarlyReflectionBuffer' in off);ok('spectral_fill',all(x in off for x in ['fillBody','fillPresence','fillTop']))
ok('hires_96k','sampleRate: 96000' in off);ok('hires_restart','case "RESTART"' in sw);ok('limiter','limiter' in off and 'ratio, 20' in off);ok('track_stop','track.stop()' in off);ok('context_close','context.close()' in off)
ok('ui_advanced',all(x in html for x in ['detail','width','reality','noiseReduction','spectralFill','hiResMode']));ok('dsd_disclaimer','真のDSD' in html)
ok('virtual_dap_ui',all(x in html for x in ['dapMode','dapStrength','Virtual DAP']))
ok('virtual_dap_core',all(x in core for x in ['DAP_MODES','dapProfile','dapStrength']))
ok('virtual_dap_nodes',all(x in off for x in ['dapPre','dapLow','dapHigh','dapShaper','dapCrossfeed']))
ok('dap_crossfeed_bounded','Math.min(0.12' in off and '1 / (1 + c)' in off)
ok('self_dap_file',(root/'self-dap-core.js').exists())
ok('self_dap_html',all(x in html for x in ['selfDapEnabled','selfDapStrength','selfDapRestoration','Self DAP']))
ok('self_dap_core',all(x in core for x in ['selfDapEnabled','selfDapStrength','selfDapRestoration']))
ok('self_dap_ms',all(x in off for x in ['createSelfDapMsStage','sideHpf','sideDelay','sidePresence']))
ok('self_dap_restoration',all(x in off for x in ['restorationShaper','restorationGain','startSelfDapMonitor']))
ok('self_dap_output_stage',all(x in off for x in ['bufferShaper','abShaper','selfLimiter']))
ok('layered_preset_core',all(x in core for x in ['PRESET_AUDIO_KEYS','VIRTUAL_DAP_KEYS','SELF_DAP_KEYS','applyPreset','sanitizeSettingsPatch','migrateStoredSettings']))
ok('revision_guard','lastSettingsRevision' in off and 'stale:true' in off and 'revision' in sw)
popup=(root/'popup.js').read_text(encoding='utf-8');ok('popup_state_engine',all(x in popup for x in ['APPLY_PATCH','APPLY_PRESET','GET_SETTINGS','SET_ENABLED']) and 'chrome.storage' not in popup);ok('sw_canonical_state',all(x in sw for x in ['canonicalSettings','canonicalRevision','enqueueAction','applyManualSettingsPatch','applyExplicitPreset']))
ok('layer_note','Virtual DAP / Self DAP / Perspective' in html)
ok('perspective_ui',all(x in html for x in ['perspectiveEnabled','perspectiveDepth','Perspective Depth']))
ok('perspective_core',all(x in core for x in ['PERSPECTIVE_KEYS','perspectiveProfile','perspectiveDepth']))
ok('perspective_nodes',all(x in off for x in ['createPerspectiveStage','createPerspectiveBuffer','ambientDelay','perspective.wet']))
ok('self_dap_true_bypass',all(x in off for x in ['bypassGain','processedGain','outputSum']))
ok('restoration_cutoff',all(x in html for x in ['selfDapRestorationCutoffKhz','9 kHz','18 kHz']) and 'selfDapRestorationCutoffKhz' in core)
ok('restoration_watchdog','watchdog-gap' in off and 'selfDapWatchdogTrips' in off and 'setInterval(updateSelfDapRestoration, 125)' in off)
ok('glitchless_master','masterSafety' in off and '0.035' in off and '0.050' in off)
ok('adaptive_safety',all(x in off for x in ['adaptiveTrim','safetyMonitorTick','-3','limiterPressureStreak']) and 'adaptiveSafetyEnabled' in core)
ok('safety_meter',all(x in off for x in ['createSafetyMeterNode','yurika-safety-meter','safetyMeterAvailable']) and 'Audio Diagnostics' in html)
ok('stereo_diagnostic','classifyStereo' in core and 'stereoCorrelation' in off and 'mono-like' in core)
ok('curve_cache','saturationCurveCache' in core)
ok('precision_decimal', 'step="0.1"' in html)
ok('dac_matrix', all(x in html for x in ['dacMatrixMode','dacMatrixStrength']) and (root/'modular-core.js').exists() and 'createDacMatrixStage' in (root/'audio-modules.js').read_text(encoding='utf-8'))
ok('room_engine', all(x in html for x in ['roomEnabled','roomMode','ARTNOVION-inspired']) and 'createRoomStage' in (root/'audio-modules.js').read_text(encoding='utf-8'))
ok('integrity_engine', all(x in html for x in ['integrityEnabled','integrityMode','Integrity Engine']))
ok('auto_level', all(x in off for x in ['autoLevelTick','sharedAnalyser','autoLevelDb']) and 'AUTO LEVEL' in html)
ok('dj_2deck', all(x in sw for x in ['ARM_DECK','STOP_DECK']) and all(x in off for x in ['ADD_DECK','stopDeck','deckNodes']) and 'DJ 2-Deck Mixer' in html)
ok('dj_auto_mix', all(x in sw for x in ['AUTO_MIX','startDjAutoMix']) and all(x in off for x in ['startDjAutoMix','djAutoMixActive','djAutoMixProgress']) and all(x in html for x in ['autoMixAB','autoMixBA','djAutoMixSeconds']))
ok('cartridge_lab', all(x in html for x in ['cartridgeAResistance','cartridgeBResistance','cartridgeCResistance','ab-split']) and 'createCartridgeStage' in (root/'audio-modules.js').read_text(encoding='utf-8'))
ok('external_input', 'START_EXTERNAL' in sw and 'startExternal' in off and 'USER_MEDIA' in sw)

ok('scene_engine_file',(root/'scene-engine.js').exists())
ok('scene_ui',all(x in html for x in ['sceneEnabled','sceneStrength','sceneExponent','sparkEnabled','deviceProfile','multiSpeakerEnabled']))
ok('scene_core',all(x in core for x in ['sceneEnabled','sceneStrength','sceneExponent','deviceProfile','multiSpeakerEnabled']))
ok('short_shared_analyser','sharedAnalyser' in off and 'transientValley.connect(autoLevel)' in off and 'output.connect(autoLevelAnalyser)' not in off)
ok('scene_runtime',all(x in off for x in ['sceneTick','sceneRuntimeNeeded','YurikaSceneEngine']))
ok('fast_spark_sidechain',all(x in off for x in ['createSparkMonitorNode','yurika-spark-monitor','transientValley.connect(sparkMonitor.node)','sparkMonitor.node.connect(sceneSink)','applyFastSparkControls']))
ok('fast_spark_no_serial_insert','transientValley.connect(autoLevel)' in off and 'sparkMonitor.node.connect(autoLevel)' not in off)
ok('additive_spark_floor',all(x in (root/'scene-engine.js').read_text(encoding='utf-8') for x in ['deriveFastSparkDelta','composeFastSparkTargets','Math.max(baseWidth','sparkGainMaxDb:0.80']))

ok('gain_arbiter_single_writer','commitEffectiveLevelGain' in off and 'composeEffectiveLevelDb' in off and off.count('smooth(nodes.autoLevel.gain')==0 and off.count('smooth(gain.gain')==1)
ok('spark_not_on_output','computeEffectiveOutputDb(state.settings) + targets.sparkMakeupDb' not in off and 'state.sparkMakeupDb' in off)
ok('gain_diagnostics',all(x in html for x in ['diagAutoLevel','diagSparkGain','diagEffectiveGain','diagLimiter']) and all(x in popup for x in ['sparkMakeupDb','effectiveLevelDb']))

ok('impact_ui',all(x in html for x in ['impactEnabled','impactAmount','Impact Liberation']))
ok('impact_core',all(x in core for x in ['impactEnabled','impactAmount']) and 'SETTINGS_SCHEMA_VERSION = 13' in core)
ok('impact_parallel_lane',all(x in off for x in ['impactHighpass','impactLowpass','impactGain']) and 'headphoneCorrection.output.connect(impactHighpass)' in off and 'impactGain.connect(output)' in off)
ok('impact_not_serial','compressor.connect(compressorProcessed)' in off and 'compressorProcessed.connect(compressorSum)' in off and 'compressorBypass.connect(compressorSum)' in off and 'compressorSum.connect(output)' in off and 'impactGain.connect(output)' in off and 'output.connect(transientValley)' in off and 'transientValley.connect(autoLevel)' in off)
ok('impact_band_limited','"highpass", 1400' in off and '"lowpass", 9000' in off)
ok('impact_safety_pressure','compressorEscape' in (root/'scene-engine.js').read_text(encoding='utf-8') and 'impactGain' in (root/'scene-engine.js').read_text(encoding='utf-8'))
ok('impact_diagnostics',all(x in html for x in ['diagImpact','diagCompEscape']) and all(x in popup for x in ['impactGain','compressorEscape']))
ok('adaptive_v26_file',(root/'adaptive-v26.js').exists() and 'YurikaAdaptiveV26' in (root/'adaptive-v26.js').read_text(encoding='utf-8'))
ok('seam_ui',all(x in html for x in ['seamNaturalizerEnabled','seamNaturalizerAmount','diagSeam']))
ok('seam_monitor_features',all(x in (root/'spark-monitor-worklet.js').read_text(encoding='utf-8') for x in ['discontinuity','speechRatio','blockDiffPeak']))
ok('valley_ui',all(x in html for x in ['transientValleyEnabled','transientValleyAmount','diagValley']))
ok('valley_unity_node','const transientValley = ctx.createGain(); transientValley.gain.value = 1' in off and 'scheduleTransientValley' in off)
ok('orbit_keeper',all(x in off for x in ['orbitKeeperTick','computeOrbitHealth','orbitHealthScore','orbitDegraded']) and 'orbitKeeperEnabled' in core)
ok('v26_off_equivalence_hooks',all(x in off for x in ['resetSeamNaturalizer','resetTransientValley']) and 'transientValley.gain.value = 1' in off)


ok('adaptive_v27_file',(root/'adaptive-v27.js').exists() and 'YurikaAdaptiveV27' in (root/'adaptive-v27.js').read_text(encoding='utf-8'))
ok('voice_material',all(x in html for x in ['voiceMaterialEnabled','voiceDepthMode','voiceTransparency','voiceAir']) and all(x in off for x in ['createVoiceMaterialStage','applyVoiceMaterial','voiceConfidence']))
ok('edge_accent',all(x in html for x in ['transientEdgeEnabled','transientEdgeAmount','transientEdgeTone']) and all(x in off for x in ['edgeAccentBand','edgeAccentGain','scheduleTransientEdge']))
ok('edge_signal_derived','headphoneCorrection.output.connect(edgeAccentBand)' in off and 'edgeAccentGain.connect(output)' in off)
ok('headphone_profiles',(root/'headphone-profiles.js').exists() and all(x in (root/'headphone-profiles.js').read_text(encoding='utf-8') for x in ['sennheiser-hd600','sony-wh1000xm5','generic-neutral']))
ok('headphone_correction',all(x in off for x in ['createHeadphoneCorrectionStage','applyHrtfAndHeadphone']) and all(x in html for x in ['headphoneCorrectionEnabled','headphoneModel','headphoneCorrectionStrength']))
ok('hrtf_split',all(x in off for x in ['createHrtfStage','crossL','crossR','delayL','delayR']) and all(x in html for x in ['hrtfEnabled','hrtfProfile','hrtfAmount']))
ok('v27_no_fixed_lookahead','createDelay(0.01)' in off and 'input.connect(split)' in off and 'directL.connect(merge' in off and 'directR.connect(merge' in off)
ok('v27_off_neutral','edgeAccentGain.gain.value = 0' in off and 'reflectionGain.gain.value = 0' in off and 'pre.gain.value=1' in off)

ok('adaptive_v28_file',(root/'adaptive-v28.js').exists() and 'YurikaAdaptiveV28' in (root/'adaptive-v28.js').read_text(encoding='utf-8'))
ok('spatial_metrics_worklet',(root/'spatial-metrics-worklet.js').exists() and all(x in (root/'spatial-metrics-worklet.js').read_text(encoding='utf-8') for x in ['itdMs','ildDb','iacc','localizationErrorProxyDeg','hrtfCueConsistency']))
ok('spatial_sidechain','headphoneCorrection.output.connect(spatialMetrics.node)' in off and 'spatialMetrics.node.connect(sceneSink)' in off)
ok('reflection_character',all(x in off for x in ['createReflectionCharacterStage','reflectionCharacter.output.connect(output)','applyReflectionCharacter']) and all(x in html for x in ['reflectionCharacterEnabled','reflectionCharacterAmount','reflectionCharacterMode']))
ok('av_sync_parallel',all(x in off for x in ['createAvSyncStage','avSync.direct','avSync.delayed']) and all(x in html for x in ['avSyncEnabled','avSyncDelayMs']))
ok('cpu_scheduler','hardwareConcurrency' in off and 'cpuProfile' in off and 'BUILD_OPTIMIZATION_V28.json' in [x.name for x in root.iterdir()])
ok('multitab_sessions',all(x in off for x in ['tabSessions','ADD_SESSION','STOP_SESSION','addSession','stopSession']) and all(x in sw for x in ['LIST_YOUTUBE_TABS','SET_TAB_SESSION','startForTab']))
ok('multitab_ui',all(x in html for x in ['multiTabList','refreshTabs','cpuSchedulerState']))
ok('v29_schema','SETTINGS_SCHEMA_VERSION = 13' in core)
ok('v29_auto_headphone',all(x in html for x in ['autoDetectHeadphone','headphoneTestTone','headphoneCalibrate','headphoneCalibrationEnabled']) and (root/'adaptive-v29.js').exists() and all(x in off for x in ['calibrationFilters','calPre','headphoneOutputSinkApplied']))
ok('v29_no_fake_measurement','Test Signalだけでは物理周波数特性は測れません' in html and '測定マイク/カプラ' in html)

# V3 Jiero guide integration
guide=(root/'v3-guide.html').read_text(encoding='utf-8')
guidejs=(root/'v3-guide.js').read_text(encoding='utf-8')
popup=(root/'popup.html').read_text(encoding='utf-8')
popupjs=(root/'popup.js').read_text(encoding='utf-8')
ok('v3_guide_page', 'ジーロ Interactive Guide' in guide and 'v3-guide.js' in guide)
ok('v3_guide_external_script', '<script>' not in guide and len(guidejs)>1000)
ok('v3_guide_popup_button', 'openV3Guide' in popup and 'v3-guide.html' in popupjs)

failed=[n for n,p in checks if not p]
for n,p in checks:print(('PASS' if p else 'FAIL'),n)
print(f'TOTAL {len(checks)} / PASS {len(checks)-len(failed)} / FAIL {len(failed)}');sys.exit(1 if failed else 0)

ok('compressor_true_bypass','compressorBypass' in off and 'compressorProcessed' in off and 'compressorEnabled' in off)
ok('self_dap_analyser_live_sink','analyser.connect(analyserSink)' in off and 'analyserSink.connect(ctx.destination)' in off)
ok('flat_lowcut_true_bypass','flat: Object.freeze({ lowCutHz:5' in dsp and 'applyLowCutRouting' in off and 'lowCutBypass' in off and 'lowCutProcessed' in off)

ok('webaudio_q_semantics','webAudioResonanceDb' in dsp and 'webAudioResonanceDb(q)' in off)
ok('selfdap_internal_limiter_bypassed','abSum.connect(processedGain)' in off and 'abSum.connect(selfLimiter)' not in off)
