"use strict";
const fs=require('fs'),path=require('path'),assert=require('assert'),{performance}=require('perf_hooks');
const root=path.resolve(__dirname,'..');require(path.join(root,'dart-detector','dart-detector-runtime.js'));
const bytes=fs.readFileSync(path.join(root,'hires-hybrid-core.wasm'));
const mod=new WebAssembly.Module(bytes);const inst=()=>new WebAssembly.Instance(mod,{}).exports;
const finite=Number.isFinite;
function configure(e,fsHz=96000,type=2){e.yurika_reset(fsHz);e.yurika_set_amount(1);e.yurika_set_detector(.55,.55,.35,.95);e.yurika_set_hierarchy_weights(.45,.4,.15,.95);e.yurika_set_object(0,type,.95,.95,.7,.5,.2);e.yurika_commit_objects(1);}
function amp(a,f,fsHz){let re=0,im=0,N=a.length;for(let n=0;n<N;n++){let q=2*Math.PI*f*n/fsHz;re+=a[n]*Math.cos(q);im-=a[n]*Math.sin(q);}return 2*Math.hypot(re,im)/N;}
function toneRun({fsHz=96000,freq=10000,nativeFreq=0,mask=7,blocks=220,type=2}){const e=inst();configure(e,fsHz,type);e.yurika_set_branch_mask(mask);const input=new Float32Array(e.memory.buffer,e.yurika_input(),512),output=new Float32Array(e.memory.buffer,e.yurika_output(),512);let p=0,p2=0,ys=[],xs=[],maxDelta=0;for(let b=0;b<blocks;b++){for(let i=0;i<128;i++){let x=.20*Math.sin(p)+(nativeFreq?0.06*Math.sin(p2):0);p=(p+2*Math.PI*freq/fsHz)%(2*Math.PI);p2=(p2+2*Math.PI*nativeFreq/fsHz)%(2*Math.PI);input[i*2]=input[i*2+1]=x;}const n=e.yurika_process(128,2);assert.equal(n,128);if(b>=Math.floor(blocks/2)){for(let i=0;i<128;i++){const x=input[i*2],y=output[i*2];assert(finite(y));const d=y-x;maxDelta=Math.max(maxDelta,Math.abs(d));xs.push(x);ys.push(y);}}}return {e,xs,ys,diff:ys.map((y,i)=>y-xs[i]),maxDelta};}
// API + reset/bounds
{const e=inst();for(const n of ['yurika_bwe_drive','yurika_sr_drive','yurika_native_hf_ratio','yurika_set_branch_mask','yurika_branch_mask'])assert.equal(typeof e[n],'function',n);e.yurika_reset(96000);assert.equal(e.yurika_controller_params(),60);e.yurika_set_branch_mask(99);assert.equal(e.yurika_branch_mask(),3);e.yurika_set_branch_mask(7);e.yurika_set_amount(NaN);e.yurika_set_detector(NaN,Infinity,-Infinity,NaN);e.yurika_set_hierarchy_weights(NaN,Infinity,-Infinity,NaN);assert(finite(e.yurika_hierarchy_weight(0))&&finite(e.yurika_hierarchy_weight(1))&&finite(e.yurika_hierarchy_weight(2)));e.yurika_reset(Infinity);assert.equal(e.yurika_process(0,2),0);const input=new Float32Array(e.memory.buffer,e.yurika_input(),512),output=new Float32Array(e.memory.buffer,e.yurika_output(),512);input.fill(0);e.yurika_process(128,2);for(let i=0;i<256;i++)assert.equal(output[i],0);input[0]=NaN;input[1]=Infinity;e.yurika_process(1,2);assert(finite(output[0])&&finite(output[1]));}
// With no committed Soft Objects the BWE-only branch must be silent.
{const e=inst();e.yurika_reset(96000);e.yurika_set_amount(1);e.yurika_set_branch_mask(4);const input=new Float32Array(e.memory.buffer,e.yurika_input(),512),output=new Float32Array(e.memory.buffer,e.yurika_output(),512);for(let i=0;i<128;i++){const x=.2*Math.sin(2*Math.PI*10000*i/96000);input[i*2]=input[i*2+1]=x;}e.yurika_process(128,2);let max=0;for(let i=0;i<128;i++)max=Math.max(max,Math.abs(output[i*2]-input[i*2]));assert(max<1e-8,'BWE must be zero before controller objects are committed');}
// Controller output bounds and hierarchy distinction
const drives=[];for(let t=0;t<4;t++){const e=inst();configure(e,96000,t);const b=e.yurika_bwe_drive(),s=e.yurika_sr_drive();assert(b>=0&&b<=1&&s>=0&&s<=1);drives.push({type:t,bwe:b,sr:s,strategy:[0,1,2,3].map(i=>e.yurika_strategy(i))});}
assert(drives[2].bwe>drives[0].bwe,'texture BWE prior should exceed tonal prior for calibration point');
// Training/runtime numerical contract: JS reference and C++ controller must agree.
{const W=JSON.parse(fs.readFileSync(path.join(root,'controller-training','controller_weights.json'),'utf8'));const lines=fs.readFileSync(path.join(root,'sr-training','audio_sr_training_data.txt'),'utf8').split(/\r?\n/).filter(x=>x&&x[0]!=='#').slice(0,24);const types={tonal:0,transient:1,texture:2,ambience:3};const fexp=x=>{x=Math.max(-7,Math.min(7,x));let y=1+x/512;for(let i=0;i<9;i++)y*=y;return y;};let maxErr=0;for(const line of lines){const o=Object.fromEntries(line.trim().split(/\s+/).map(t=>t.split('=',2)));const t=types[o.type],x=[+o.energy,+o.confidence,+o.l1,+o.l2,+o.l3,0,0,0,0];x[5+t]=1;const raw=W.WS.map((w,k)=>fexp(W.BS[k]+w.reduce((a,v,i)=>a+v*x[i],0))),sum=raw.reduce((a,b)=>a+b,0),ref=[...raw.map(v=>v/sum),...W.WC.map((w,k)=>1/(1+fexp(-(W.BC[k]+w.reduce((a,v,i)=>a+v*x[i],0)))))];const e=inst();e.yurika_reset(96000);e.yurika_set_object(0,t,+o.energy,+o.confidence,+o.l1,+o.l2,+o.l3);e.yurika_commit_objects(1);const got=[0,1,2,3].map(i=>e.yurika_strategy(i)).concat([e.yurika_bwe_drive(),e.yurika_sr_drive()]);for(let i=0;i<6;i++)maxErr=Math.max(maxErr,Math.abs(got[i]-ref[i]));}assert(maxErr<2e-5,'training/runtime controller float32 parity mismatch: '+maxErr);global.controllerParity=maxErr;}
// BWE-only branch must synthesize a component above a 48 kHz source Nyquist.
const low=toneRun({freq:10000,mask:4});const a30=amp(low.diff,30000,96000),a10=amp(low.diff,10000,96000);assert(a30>2e-6,'BWE branch did not generate measurable 30 kHz energy');assert(low.maxDelta<=.025001,'injection clamp exceeded');
// Native-high-band protection should reduce BWE when a real 30 kHz component already exists.
const native=toneRun({freq:10000,nativeFreq:30000,mask:4});const n30=amp(native.diff,30000,96000);assert(native.e.yurika_native_hf_ratio()>low.e.yurika_native_hf_ratio()*2.5,'native HF detector lacks separation');assert(n30<a30*.85,'native HF protection failed to reduce BWE branch');
// Sample-rate coverage and numerical stability.
const rates={};for(const sr of [88200,96000,176400,192000]){const r=toneRun({fsHz:sr,freq:Math.min(10000,sr*.10),mask:7,blocks:80});rates[sr]={maxDelta:r.maxDelta,bwe:r.e.yurika_bwe_drive(),sr:r.e.yurika_sr_drive(),native:r.e.yurika_native_hf_ratio()};assert(r.maxDelta<=.025001);}
// Dart time constants must be rate-aware for same elapsed time.
const da=globalThis.YurikaDartDetectorRuntime.create(),db=globalThis.YurikaDartDetectorRuntime.create();let pa,pb;for(let i=0;i<400;i++){const m={rms:.10+.02*Math.sin(i*.07),peak:.32,diffRms:.012,zeroCrossRate:.035,sideRatio:.25};pa=da.process({...m,sampleRate:96000,frames:512});pb=db.process({...m,sampleRate:48000,frames:256});}const rateDiff=Math.max(Math.abs(pa.hierarchyWeights.l1-pb.hierarchyWeights.l1),Math.abs(pa.hierarchyWeights.l2-pb.hierarchyWeights.l2),Math.abs(pa.hierarchyWeights.l3-pb.hierarchyWeights.l3));assert(rateDiff<1e-9);
// Deterministic processing cost probe at 96 kHz.
{const e=inst();configure(e);const input=new Float32Array(e.memory.buffer,e.yurika_input(),512);let ph=0;const times=[];for(let b=0;b<12000;b++){for(let i=0;i<128;i++){const x=.12*Math.sin(ph)+.04*Math.sin(ph*.37);ph=(ph+2*Math.PI*997/96000)%(2*Math.PI);input[i*2]=x;input[i*2+1]=x*.98;}const t0=performance.now();e.yurika_process(128,2);if(b>200)times.push(performance.now()-t0);}times.sort((a,b)=>a-b);const mean=times.reduce((a,b)=>a+b,0)/times.length,p95=times[Math.floor(times.length*.95)],p99=times[Math.floor(times.length*.99)];global.perf={mean,p95,p99,max:times.at(-1)};}
console.log(JSON.stringify({ok:true,controllerParityMaxAbsError:global.controllerParity,controllerDrives:drives,bweOnly:{a10,a30,nativeRatio:low.e.yurika_native_hf_ratio()},nativeProtect:{a30:n30,nativeRatio:native.e.yurika_native_hf_ratio(),reduction:n30/a30},sampleRates:rates,dartRateAwareMaxWeightDiff:rateDiff,processMs:global.perf}));
